### Lamda Function

In [ ]:
# lambda arg:expression

In [1]:
def add(a):
    print(a%2==0)
add(10)

True

In [2]:
y=lambda x:x%2==0
y(10)

True

In [3]:
sum=lambda x,y:x+y
sum(5,8)

13

In [11]:
even=lambda x:'even' if x%2==0 else 'odd'
print(even(12))

even

### Filter Function

In [ ]:
# list(filter(lambda arg:exp,data))

In [13]:
l=[1,2,3,4,5,6,7]
y=list(filter(lambda x:2,l))
print(y)

[1, 2, 3, 4, 5, 6, 7]

In [12]:
l=[1,2,3,4,5,6,7]
y=list(filter(lambda x:x%2==0,l))
print(y)

[2, 4, 6]

In [ ]:
## map
# adding each by 3

In [14]:
l=[1,2,3,4,5,6,7]
y=list(map(lambda x:x+3,l))
print(y)

[4, 5, 6, 7, 8, 9, 10]

In [15]:
# wap to apply a 15 % discount on a list of product prices using the map() function and lambda function.
list1=[500,1999,456,445,600,500,200]
discount=list(map(lambda x: x-x*0.15,list1))
print(f' with 15% discount list : {discount}')

 with 15% discount list : [425.0, 1699.15, 387.6, 378.25, 510.0, 425.0, 170.0]

In [18]:
##  wap to convert all words in a list into uppercase using map() function and lambda function

list2=['lokendra','binaya','rajkumar','hello','bishal']
uppercase=list(map(lambda name: name.upper(),list2))
print(uppercase)

['LOKENDRA', 'BINAYA', 'RAJKUMAR', 'HELLO', 'BISHAL']

In [23]:
## Reduce
# reduce(function ,operation)
from functools import reduce
lis=[1,2,3,4,5,6,7]
data=reduce(lambda a,b:a+b,lis)
print(data)

28

In [24]:
# largest
list3=[1,2,3,4,5,6,7]
largest=reduce(lambda a,b:a if a>b else b,list3)
print(largest)

7

In [34]:
list3=[1,2,3,4,5,6,7]
largest=reduce(lambda a,b:a if a>b else b,list3)
second_largest=reduce(lambda a,b:a if a>b else b,[x for x in list3 if x!=largest])
print(second_largest)

6

In [ ]:
#     keyword

In [ ]:
# *args allows a function to accept any number of arguments

In [1]:
def total(*a):
    print(sum(a))
total(1,23,4,5,6,7,8,9)

63

In [2]:
def total(**a):
    print(a)
total(name='lokendra',age=20)

{'name': 'lokendra', 'age': 20}

In [ ]:
# python Libraries

In [3]:
import os
print(os.getcwd())

D:\python\Python-basic-to-advance\Basic Python\code\Oop

In [8]:
import random 
print(random.randint(1,10))

1

In [ ]:
## Pandas

In [12]:
import pandas as pd

In [13]:

print(pd.__version__)

2.3.3

In [15]:
import pandas as pd

data = {
    'Name': [
        'Ram', 'Hari', 'Sita', 'Gita', 'Shyam', 
        'Laxmi', 'Bikash', 'Aayush', 'Pooja', 'Suman', 
        'Anish', 'Rina', 'Kiran', 'Nirajan', 'Sabina', 
        'Dipesh', 'Sunita', 'Roshan', 'Sarita', 'Aashish'
    ],
    'age': [
        20, 40, 35, 28, 22, 
        45, 30, 25, 27, 33, 
        24, 29, 31, 38, 26, 
        42, 36, 23, 48, 21
    ],
    'address': [
        'Kathmandu', 'Lalitpur', 'Bhaktapur', 'Kathmandu', 'Lalitpur', 
        'Bhaktapur', 'Kathmandu', 'Kirtipur', 'Lalitpur', 'Kathmandu', 
        'Bhaktapur', 'Banepa', 'Kathmandu', 'Lalitpur', 'Bhaktapur', 
        'Kirtipur', 'Kathmandu', 'Lalitpur', 'Bhaktapur', 'Kathmandu'
    ]
}

df = pd.DataFrame(data)
print(df)

       Name  age    address
0       Ram   20  Kathmandu
1      Hari   40   Lalitpur
2      Sita   35  Bhaktapur
3      Gita   28  Kathmandu
4     Shyam   22   Lalitpur
5     Laxmi   45  Bhaktapur
6    Bikash   30  Kathmandu
7    Aayush   25   Kirtipur
8     Pooja   27   Lalitpur
9     Suman   33  Kathmandu
10    Anish   24  Bhaktapur
11     Rina   29     Banepa
12    Kiran   31  Kathmandu
13  Nirajan   38   Lalitpur
14   Sabina   26  Bhaktapur
15   Dipesh   42   Kirtipur
16   Sunita   36  Kathmandu
17   Roshan   23   Lalitpur
18   Sarita   48  Bhaktapur
19  Aashish   21  Kathmandu

In [17]:
df.to_csv("student.csv",index=False)

In [19]:
data=pd.read_csv("student.csv")
data.head(2)

   Name  age    address
0   Ram   20  Kathmandu
1  Hari   40   Lalitpur

In [20]:
data.tail(2)

       Name  age    address
18   Sarita   48  Bhaktapur
19  Aashish   21  Kathmandu

In [21]:
data=pd.read_csv('student.csv',nrows=3)
data

   Name  age    address
0   Ram   20  Kathmandu
1  Hari   40   Lalitpur
2  Sita   35  Bhaktapur

In [29]:
data=pd.read_csv('student.csv',nrows=3, usecols=['Name','address'],index_col='Name')
data

        address
Name
Ram   Kathmandu
Hari   Lalitpur
Sita  Bhaktapur